-- Native GMGN condition-orders (server-side trailing-stop/stop-loss) για live trades,
-- 2026-09-17 — απάντηση στο πραγματικό incident #1193 (βλ. σχόλια στο
-- realtimeExitHandler.ts και paperTrades.ts's selectOpenTradesForCheck).
--
-- Το δικό μας websocket-based tracking (tickExit.ts) εξαρτάται εξ ολοκλήρου από το να
-- είναι το δικό μας process ζωντανό ΚΑΙ το PumpPortal feed να καλύπτει το token —
-- και τα δύο απέτυχαν ταυτόχρονα στο #1193. Το GMGN CLI υποστηρίζει ήδη native
-- `profit_stop_trace`/`loss_stop` condition orders, που εκτελούνται στη ΔΙΚΗ ΤΟΥΣ
-- υποδομή, ανεξάρτητα από το αν είμαστε online.
--
-- ΔΙΟΡΘΩΣΗ, ΙΔΙΑ ΜΕΡΑ (ρητή απόφαση χρήστη, μετά το πρώτο deploy αυτού του migration):
-- το native order ΔΕΝ είναι το πρωτεύον exit mechanism — παραμένει ο δικός μας
-- websocket-based tracker (realtimeExitHandler.ts's decideForTick), ΑΚΡΙΒΩΣ ίδια
-- λογική με το paper trading, χωρίς καμία εξαίρεση όταν native_order_active=true. Ο
-- λόγος: το paper trading υπάρχει για να δοκιμάσει ΑΥΤΟΝ τον μηχανισμό — live με
-- διαφορετική πρωτεύουσα λογική θα σήμαινε ότι η δοκιμή στο paper δεν αντιστοιχεί σε
-- ό,τι τελικά αποφασίζει με πραγματικά λεφτά. Το native order μένει συνδεδεμένο ΜΟΝΟ
-- ως ασφάλεια/dead-man's-switch για την περίπτωση που πέσει το δικό μας process/feed.
--
-- `live_strategy_order_id`: το strategy_order_id που επέστρεψε το `swap
-- --condition-orders` στο entry — NULL για paper/log_only, ή για live trades όπου η
-- δημιουργία απέτυχε εντελώς (best-effort, βλ. SKILL.md).
--
-- `native_order_active`: true ΜΟΝΟ όταν επιβεβαιώσαμε (αμέσως μετά το entry, μέσω
-- `order strategy list`) ότι το strategy είναι πράγματι `running` ΚΑΙ κανένα
-- υπο-order δεν είναι `failed`. ΔΕΝ αλλάζει τη λογική του decideForTick (βλ. διόρθωση
-- πιο πάνω) — μόνο σηματοδοτεί ότι υπάρχει native order να ακυρωθεί πριν από τη δική
-- μας πώληση, και ότι ο live strategy reconciler (νέο periodic collector) πρέπει να
-- το παρακολουθεί. Ο reconciler το γυρίζει σε false αν το strategy αποτύχει/σταματήσει
-- χωρίς να κλείσει τη θέση.
ALTER TABLE paper_trades ADD COLUMN live_strategy_order_id TEXT;
ALTER TABLE paper_trades ADD COLUMN native_order_active BOOLEAN NOT NULL DEFAULT false;
